### ISSUE TITLE
Cannot Compile on Windows 7 64bit with VS 2013 Community\Pro

### ISSUE THREAD

**Issue by Vanderemit** [OctaForge/OF-Engine#31]
I have the required files from OF-Windows already copied to the appropriate directories.
Here's the error log. 

Warning	1	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	C:\Game_Development\Octaforge(Impure)\src\engine\command.cpp	4404	1	octaforge
Warning	2	warning C4800: 'SDL_bool' : forcing value to bool 'true' or 'false' (performance warning)	C:\Game_Development\Octaforge(Impure)\src\engine\console.cpp	318	1	octaforge
Warning	3	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	C:\Game_Development\Octaforge(Impure)\src\engine\console.cpp	918	1	octaforge
Warning	4	warning C4800: 'const short' : forcing value to bool 'true' or 'false' (performance warning)	C:\Game_Development\Octaforge(Impure)\src\engine\physics.cpp	810	1	octaforge
Warning	5	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	C:\Game_Development\Octaforge(Impure)\src\engine\rendergl.cpp	2759	1	octaforge
Warning	6	warning C4065: switch statement contains 'default' but no 'case' labels	C:\Game_Development\Octaforge(Impure)\src\engine\server.cpp	1153	1	octaforge
Warning	7	warning C4189: 'loadingstart' : local variable is initialized but not referenced	C:\Game_Development\Octaforge(Impure)\src\engine\worldio.cpp	599	1	octaforge
Warning	8	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	C:\Game_Development\Octaforge(Impure)\src\octaforge\of_lua.cpp	533	1	octaforge
Warning	9	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	C:\Game_Development\Octaforge(Impure)\src\octaforge\of_lua.cpp	815	1	octaforge
Error	10	error C2121: '#' : invalid character : possibly the result of a macro expansion	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge
Error	11	error C2065: 'ifndef' : undeclared identifier	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge
Error	12	error C2146: syntax error : missing ';' before identifier 'STANDALONE'	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge
Error	13	error C2065: 'STANDALONE' : undeclared identifier	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge
Error	14	error C2143: syntax error : missing ';' before 'if'	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge
Error	15	error C2065: 'endif' : undeclared identifier	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge
Error	16	error C2143: syntax error : missing ';' before 'const'	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge
Error	17	error C2065: 'found' : undeclared identifier	C:\Game_Development\Octaforge(Impure)\src\shared\stream.cpp	567	1	octaforge

**Comment by q66** [comment]
fixed by @b66f710 and @b71d03d.
